@echo off
REM Batch script to launch python
REM --- Configuration ---

REM Path to your main entrypoint and venv  (using relative path from script location)
SET "VENV_PATH=C:\src\repos\PytorchDL\.venv\Scripts\activate.bat"
SET "MAIN_PY=C:\src\repos\PytorchDL\main.py"
REM Args for main scripts
SET "MODULE=data_utility"
SET "MODE=create_subsets"
SET "JOB_LOCATION=H:\ABC\ABC_jobs\torch_job_chunk_01"
SET "INPUT_DIR=H:\ABC\ABC_Datasets\Segmentation\ABC_Chunk_01\ABC_Data_ks_16_pad_4_bw_5_vs_adaptive_n2"
SET "OUTPUT_DIR=H:\ABC\ABC_torch\ABC_chunk_01\torch_data_ks_16_pad_4_bw_5_vs_adaptive_n2"
SET "MIN_FILES=2"


call %VENV_PATH%

SET "ID=001"
SET "INSTANCE_ID=Instance%ID%"
SET "JOB_FILE=%JOB_LOCATION%\%INSTANCE_ID%.job"
START "%INSTANCE_ID% Process"/B %MAIN_PY% %MODULE% %MODE% %JOB_FILE% %INPUT_DIR% %OUTPUT_DIR% %MIN_FILES%

SET "ID=002"
SET "INSTANCE_ID=Instance%ID%"
SET "JOB_FILE=%JOB_LOCATION%\%INSTANCE_ID%.job"
START "%INSTANCE_ID% Process"/B %MAIN_PY% %MODULE% %MODE% %JOB_FILE% %INPUT_DIR% %OUTPUT_DIR% %MIN_FILES%

SET "ID=003"
SET "INSTANCE_ID=Instance%ID%"
SET "JOB_FILE=%JOB_LOCATION%\%INSTANCE_ID%.job"
START "%INSTANCE_ID% Process"/B %MAIN_PY% %MODULE% %MODE% %JOB_FILE% %INPUT_DIR% %OUTPUT_DIR% %MIN_FILES%

SET "ID=004"
SET "INSTANCE_ID=Instance%ID%"
SET "JOB_FILE=%JOB_LOCATION%\%INSTANCE_ID%.job"
START "%INSTANCE_ID% Process"/B %MAIN_PY% %MODULE% %MODE% %JOB_FILE% %INPUT_DIR% %OUTPUT_DIR% %MIN_FILES%

SET "ID=005"
SET "INSTANCE_ID=Instance%ID%"
SET "JOB_FILE=%JOB_LOCATION%\%INSTANCE_ID%.job"
START "%INSTANCE_ID% Process"/B %MAIN_PY% %MODULE% %MODE% %JOB_FILE% %INPUT_DIR% %OUTPUT_DIR% %MIN_FILES%

SET "ID=006"
SET "INSTANCE_ID=Instance%ID%"
SET "JOB_FILE=%JOB_LOCATION%\%INSTANCE_ID%.job"
START "%INSTANCE_ID% Process"/B %MAIN_PY% %MODULE% %MODE% %JOB_FILE% %INPUT_DIR% %OUTPUT_DIR% %MIN_FILES%

SET "ID=007"
SET "INSTANCE_ID=Instance%ID%"
SET "JOB_FILE=%JOB_LOCATION%\%INSTANCE_ID%.job"
START "%INSTANCE_ID% Process"/B %MAIN_PY% %MODULE% %MODE% %JOB_FILE% %INPUT_DIR% %OUTPUT_DIR% %MIN_FILES%

SET "ID=008"
SET "INSTANCE_ID=Instance%ID%"
SET "JOB_FILE=%JOB_LOCATION%\%INSTANCE_ID%.job"
START "%INSTANCE_ID% Process"/B %MAIN_PY% %MODULE% %MODE% %JOB_FILE% %INPUT_DIR% %OUTPUT_DIR% %MIN_FILES%

SET "ID=009"
SET "INSTANCE_ID=Instance%ID%"
SET "JOB_FILE=%JOB_LOCATION%\%INSTANCE_ID%.job"
START "%INSTANCE_ID% Process"/B %MAIN_PY% %MODULE% %MODE% %JOB_FILE% %INPUT_DIR% %OUTPUT_DIR% %MIN_FILES%

SET "ID=010"
SET "INSTANCE_ID=Instance%ID%"
SET "JOB_FILE=%JOB_LOCATION%\%INSTANCE_ID%.job"
START "%INSTANCE_ID% Process"/B %MAIN_PY% %MODULE% %MODE% %JOB_FILE% %INPUT_DIR% %OUTPUT_DIR% %MIN_FILES%

SET "ID=011"
SET "INSTANCE_ID=Instance%ID%"
SET "JOB_FILE=%JOB_LOCATION%\%INSTANCE_ID%.job"
START "%INSTANCE_ID% Process"/B %MAIN_PY% %MODULE% %MODE% %JOB_FILE% %INPUT_DIR% %OUTPUT_DIR% %MIN_FILES%

SET "ID=012"
SET "INSTANCE_ID=Instance%ID%"
SET "JOB_FILE=%JOB_LOCATION%\%INSTANCE_ID%.job"
START "%INSTANCE_ID% Process"/B %MAIN_PY% %MODULE% %MODE% %JOB_FILE% %INPUT_DIR% %OUTPUT_DIR% %MIN_FILES%

SET "ID=013"
SET "INSTANCE_ID=Instance%ID%"
SET "JOB_FILE=%JOB_LOCATION%\%INSTANCE_ID%.job"
START "%INSTANCE_ID% Process"/B %MAIN_PY% %MODULE% %MODE% %JOB_FILE% %INPUT_DIR% %OUTPUT_DIR% %MIN_FILES%

SET "ID=014"
SET "INSTANCE_ID=Instance%ID%"
SET "JOB_FILE=%JOB_LOCATION%\%INSTANCE_ID%.job"
START "%INSTANCE_ID% Process"/B %MAIN_PY% %MODULE% %MODE% %JOB_FILE% %INPUT_DIR% %OUTPUT_DIR% %MIN_FILES%

SET "ID=015"
SET "INSTANCE_ID=Instance%ID%"
SET "JOB_FILE=%JOB_LOCATION%\%INSTANCE_ID%.job"
START "%INSTANCE_ID% Process"/B %MAIN_PY% %MODULE% %MODE% %JOB_FILE% %INPUT_DIR% %OUTPUT_DIR% %MIN_FILES%

SET "ID=016"
SET "INSTANCE_ID=Instance%ID%"
SET "JOB_FILE=%JOB_LOCATION%\%INSTANCE_ID%.job"
START "%INSTANCE_ID% Process"/B %MAIN_PY% %MODULE% %MODE% %JOB_FILE% %INPUT_DIR% %OUTPUT_DIR% %MIN_FILES%

pause